### ISSUE TITLE
Change the key for The Graph

### ISSUE THREAD

**Issue by alainncls** [Consensys/linea-ens#262]
## Description

The key we're currently using to call The Graph from the Linea ENS frontend needs to be changed.

## Motivation

This change is required in light of the contract change with The Graph, to avoid any interruption of service on the Linea ENS service.

## Tasks

- [x] Grab the new key for The Graph
- [x] Replace it in the config
- [ ] ~~Replace it in codebase of the Linea ENS frontend~~
- [x] Deploy & Test on Devnet
- [ ] Deploy & Test on Sepolia
- [ ] Deploy & Test on Mainnet

## Acceptance criteria

- [ ] The key should be injected at a config level as much as possible
- [x] The frontend should still be able to fetch already registered names for a user
- [x] The call made to The Graph API should use the new key

## Risks

- [ ] Waiting too long to make this change can result in the frontend being unusable (previous key reaching its quota)
